# you can override this using by setting a system property, for example -Des.logger.level=DEBUG
es.logger.level: debug
rootLogger: ${es.logger.level}, file, console
logger:
  # log action execution errors for easier debugging
  action: DEBUG

  org.apache.http: INFO
  org.apache.bookkeeper: ERROR
  org.apache.zookeeper: ERROR
  com.twitter: ERROR

  # gateway
  #gateway: DEBUG
  #index.gateway: DEBUG

  # peer shard recovery
  #indices.recovery: DEBUG

  # discovery
  #discovery: TRACE

  index.search.slowlog: TRACE, index_search_slow_log_file
  index.indexing.slowlog: TRACE, index_indexing_slow_log_file

  # auditlog
  auditlog: INFO, auditlog_log_file

additivity:
  index.search.slowlog: false
  index.indexing.slowlog: false
  auditlog: false
  
  
appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  file:
    type: rollingFile
    file: ${path.logs}/${cluster.name}.log
    MaxFileSize: 1GB
    MaxBackupIndex: 30
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %.10000m%n"

  index_search_slow_log_file:
    type: rollingFile
    file: ${path.logs}/${cluster.name}_index_search_slowlog.log
    MaxFileSize: 100MB
    MaxBackupIndex: 10
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  index_indexing_slow_log_file:
    type: rollingFile
    file: ${path.logs}/${cluster.name}_index_indexing_slowlog.log
    MaxFileSize: 100MB
    MaxBackupIndex: 10
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

  auditlog_log_file:
    type: rollingFile
    file: ${path.logs}/${cluster.name}_auditlog.log
    MaxFileSize: 1GB
    MaxBackupIndex: 30
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
